### ISSUE TITLE
Where are the tweets?

### ISSUE THREAD

**Issue by dekacypher** [Rakibul73/twitter_tweets_api#1]
Hi! I've successfully deployed the app, but then i only get up an empty page with "Welcome to the Twitter Tweets API!". 
I don't understand where can i fetch the tweets?

**Comment by Rakibul73** [comment]
![image](https://github.com/Rakibul73/twitter_tweets_api/assets/72851692/186f5892-0c57-4cb6-be68-c2900387e747)

![image](https://github.com/Rakibul73/twitter_tweets_api/assets/72851692/8f584899-86a7-4edf-ae4f-a5ce2a8fd27f)

I used `tweepy` library and used `user_timeline` method to fetch last latest tweet of a user. 
But as you can see in that pic, last month twitter change their policy and made that endpoint premium. so unfortunately , it won't work unless I pay.
I plan on changing the procedure for obtaining the most recent tweet. But lately, I've been busy with studying for an upcoming academic exam.

But before when it worked.. 
you can go to for localhost =  http://127.0.0.1:5000//latest_tweet/xdadevelopers and see the latest tweet of xdadevelopers user . you could change it to any username


ALSO ... You should use your own api key, secret etc if you have premium access. Then you can just replace those key with yours and use it like before

**Comment by dekacypher** [comment]
Thanks for the reply, that makes sense why it didn't work. I'll find a solution and i wish you good luck on your exam!
